import { Injectable } from '@angular/core';
import { Recipe } from '../models/recipe.model';

@Injectable({
  providedIn: 'root',
})
export class recipesService {
  recipes: Recipe[] = [
    {
      id: 1,
      stars: 5,
      name: 'Maki au thon',
      image: 'https://www.example.com/thon-maki.jpg',
      author: 'John Doe',
      datePublished: '2023-01-30',
      description:
        "Les makis au thon sont des rouleaux de sushi remplis de thon cru, de riz et d'algues nori.",
      prepTime: 'PT20M',
      cookTime: 'PT10M',
      totalTime: 'PT30M',
      recipeYield: '4 portions',
      recipeCategory: 'Plat principal',
      recipeCuisine: 'Japonaise',
      nutrition: {
        calories: '250 calories',
      },
      recipeIngredient: [
        '200g de thon cru',
        '2 tasses de riz à sushi',
        "4 feuilles d'algues nori",
        '1 avocat',
        '1 concombre',
        '1/4 tasse de vinaigre de riz',
        '1 cuillère à soupe de sucre',
        '1 cuillère à soupe de sel',
      ],
      recipeInstructions: [
        "Cuire le riz à sushi selon les instructions sur l'emballage.",
        'Mélanger le vinaigre de riz, le sucre et le sel dans une petite casserole.',
        "Chauffer à feu moyen jusqu'à ce que le sucre et le sel soient dissous.",
        'Laisser refroidir complètement.',
        "Couper le thon, l'avocat et le concombre en fines lanières.",
        "Placer une feuille d'algue nori sur un tapis à sushi en bambou.",
        "Étaler une couche uniforme de riz sur l'algue nori, en laissant une bordure de 1 cm à l'extrémité supérieure.",
        "Disposer les lanières de thon, d'avocat et de concombre en une ligne sur le riz.",
        'Rouler le tapis à sushi pour former un rouleau serré.',
        'Couper le rouleau en tranches égales avec un couteau tranchant et humide.',
      ],
    },
    {
      id: 2,
      stars: 5,
      name: 'Ramen Maison',
      image: 'https://www.example.com/ramen.jpg',
      author: 'John Doe',
      datePublished: '2023-01-30',
      description:
        'Un délicieux ramen fait maison avec des nouilles fraîches, du bouillon savoureux et des ingrédients de qualité supérieure.',
      prepTime: 'PT30M',
      cookTime: 'PT1H',
      totalTime: 'PT1H30M',
      recipeYield: '4 portions',
      recipeCategory: 'Plat principal',
      recipeCuisine: 'Japonaise',
      nutrition: {
        calories: '500 calories',
      },
      recipeIngredient: [
        '4 tasses de bouillon de poulet',
        '4 portions de nouilles de ramen',
        '8 tranches de viande de porc',
        '1 bouquet de bok choy',
        "2 gousses d'ail hachées",
        '2 cuillères à soupe de sauce soja',
        '2 cuillères à soupe de vinaigre de riz',
        '1 cuillère à soupe de sucre',
        "2 cuillères à soupe d'huile de sésame",
        '2 oeufs pochés',
        'germes de soja, pour garnir',
      ],
      recipeInstructions: [
        'Dans une casserole, faire bouillir le bouillon de poulet.',
        'Ajouter les nouilles de ramen et la viande de porc et cuire pendant 3 minutes.',
        "Ajouter le bok choy, l'ail haché, la sauce soja, le vinaigre de riz, le sucre et l'huile de sésame.",
        "Servir dans des bols et garnir de germes de soja et d'œufs pochés.",
        'Bon appétit!',
      ],
    },
    {
      id: 3,
      stars: 5,
      name: 'Bò Bún Maison',
      image: 'https://www.example.com/bobun.jpg',
      author: 'John Doe',
      datePublished: '2023-01-30',
      description:
        'Un délicieux bò bún fait maison avec des nouilles fraîches, des ingrédients frais et des sauces délicieuses.',
      prepTime: 'PT30M',
      cookTime: 'PT15M',
      totalTime: 'PT45M',
      recipeYield: '4 portions',
      recipeCategory: 'Plat principal',
      recipeCuisine: 'Vietnamienne',
      nutrition: {
        calories: '400 calories',
      },
      recipeIngredient: [
        '1 kilogramme de viande de bœuf coupée en fines tranches',
        '4 portions de nouilles de riz',
        '1 tasse de vermicelles de soja',
        '1 bouquet de menthe fraîche',
        '1 bouquet de coriandre fraîche',
        '1 oignon vert haché',
        "1 gousse d'ail hachée",
        '1 cuillère à soupe de sucre',
        '2 cuillères à soupe de nuoc mam (sauce de poisson)',
        '2 cuillères à soupe de sauce hoisin',
        "2 cuillères à soupe d'huile de sésame",
        '1 citron vert, coupé en quartiers',
        'piments rouges frais, pour garnir',
      ],
      recipeInstructions: [
        "Faire bouillir les nouilles de riz et les vermicelles de soja séparément jusqu'à ce qu'ils soient cuits.",
        "Dans une poêle, faire dorer la viande de bœuf dans l'huile de sésame.",
        "Ajouter l'ail haché et l'oignon vert haché et faire cuire pendant 2 minutes.",
        'Dans un bol, mélanger le sucre, la nuoc mam, la sauce hoisin et le jus de citron vert.',
        'Servir les nouilles de riz dans des bols, ajouter la viande de bœuf dessus, puis les vermicelles de soja et les herbes fraîches.',
        'Verser la sauce sur le dessus et garnir de piments rouges frais.',
        'Bon appétit!',
      ],
    },
    {
      id: 4,
      stars: 5,
      name: 'Bibimbap Maison',
      image: 'https://www.example.com/bibimbap.jpg',
      author: 'Jane Doe',
      datePublished: '2023-01-30',
      description:
        'Un délicieux bibimbap fait maison avec des ingrédients frais et des sauces délicieuses.',
      prepTime: 'PT30M',
      cookTime: 'PT15M',
      totalTime: 'PT45M',
      recipeYield: '4 portions',
      recipeCategory: 'Plat principal',
      recipeCuisine: 'Coréenne',
      nutrition: {
        calories: '400 calories',
      },
      recipeIngredient: [
        '4 portions de riz japonais cuit',
        '1 kilogramme de viande de bœuf coupée en fines tranches',
        '4 oeufs',
        '1 tasse de champignons en tranches',
        '1 tasse de carottes râpées',
        '1 tasse de chou chinois en tranches',
        '1 tasse de germes de soja',
        "2 cuillères à soupe d'huile de sésame",
        '1 cuillère à soupe de sucre',
        '2 cuillères à soupe de gochujang (pâte de piment rouge coréenne)',
        '2 cuillères à soupe de vinaigre de riz',
        '1 cuillère à soupe de sauce soja',
        '1 citron vert, coupé en quartiers',
      ],
      recipeInstructions: [
        "Dans une poêle, faire dorer la viande de bœuf dans l'huile de sésame.",
        'Dans une autre poêle, faire cuire les oeufs en omelette et les couper en lanières.',
        "Faire sauter les champignons, les carottes, le chou chinois et les germes de soja dans de l'huile de sésame jusqu'à ce qu'ils soient tendres.",
        'Dans un bol, mélanger le sucre, le gochujang, le vinaigre de riz et la sauce soja.',
        'Dans chaque bol, disposer une portion de riz japonais cuit, puis une portion de chaque légume et de la viande de bœuf.',
        "Verser la sauce sur le dessus et garnir de lanières d'omelette et de quartiers de citron vert.",
        'Bon appétit!',
      ],
    },
    {
      id: 4,
      stars: 5,
      name: 'Banh Bao Maison',
      image: 'https://www.example.com/banhbao.jpg',
      author: 'Jane Doe',
      datePublished: '2023-01-30',
      description:
        'Des banh bao moelleux et savoureux faits maison avec une farce délicieuse.',
      prepTime: 'PT1H',
      cookTime: 'PT30M',
      totalTime: 'PT1H30M',
      recipeYield: '12 banh bao',
      recipeCategory: 'Plat principal',
      recipeCuisine: 'Vietnamienne',
      nutrition: {
        calories: '200 calories par banh bao',
      },
      recipeIngredient: [
        '3 tasses de farine tout usage',
        '1 sachet de levure instantanée',
        '1/4 tasse de sucre en poudre',
        '1 pincée de sel',
        "1/4 tasse d'huile végétale",
        "1/2 tasse d'eau chaude",
        '1 oeuf, battu',
        '1 tasse de porc haché',
        '1 tasse de champignons en tranches',
        "1 tasse d'oignons verts hachés",
        '1 cuillère à soupe de sauce soja',
        '1 cuillère à soupe de sucre',
        '1 cuillère à soupe de vinaigre de riz',
      ],
      recipeInstructions: [
        'Dans un grand bol, mélanger la farine, la levure, le sucre en poudre et le sel.',
        "Ajouter l'huile végétale et l'eau chaude, puis l'œuf battu et mélanger jusqu'à ce que la pâte soit lisse.",
        'Couvrir le bol avec un linge propre et laisser lever pendant 1 heure.',
        "Dans une poêle, faire cuire le porc haché jusqu'à ce qu'il soit bien doré, puis ajouter les champignons, les oignons verts, la sauce soja, le sucre et le vinaigre de riz et mélanger jusqu'à ce que les ingrédients soient bien incorporés.",
        "Diviser la pâte en 12 portions égales et étaler chaque portion en un cercle d'environ 10 cm de diamètre.",
        'Ajouter une portion de farce au centre de chaque cercle de pâte et replier les bords vers le centre pour former un boudin.',
        'Placer les banh bao dans un moule à muffins graissé et laisser lever pendant 15 minutes.',
      ],
    },
    {
      id: 5,
      stars: 5,
      name: 'Nems Aux Porcs Faits Maison',
      image: 'https://www.example.com/nemsporc.jpg',
      author: 'Jane Doe',
      datePublished: '2023-01-30',
      description:
        'Des nems aux porcs croustillants et savoureux faits maison avec une farce délicieuse.',
      prepTime: 'PT30M',
      cookTime: 'PT15M',
      totalTime: 'PT45M',
      recipeYield: '12 nems',
      recipeCategory: 'Plat principal',
      recipeCuisine: 'Vietnamienne',
      nutrition: {
        calories: '200 calories par nem',
      },
      recipeIngredient: [
        '300g de porc haché',
        '1 oignon haché',
        "2 gousses d'ail hachées",
        '1 cuillère à soupe de sauce soja',
        '1 cuillère à soupe de sucre',
        '1 cuillère à soupe de vinaigre de riz',
        '1 pincée de sel',
        '1 pincée de poivre',
        '12 feuilles de brick',
      ],
      recipeInstructions: [
        "Dans un grand bol, mélanger le porc haché, l'oignon, l'ail, la sauce soja, le sucre, le vinaigre de riz, le sel et le poivre.",
        'Prechauffer le four à 180°C.',
        'Placer une feuille de brick sur le plan de travail et déposer environ 2 cuillères à soupe de farce au centre de la feuille.',
        "Rouler la feuille de brick autour de la farce pour former un nem et le sceller avec un peu d'eau.",
        "Répéter l'opération avec les 11 autres feuilles de brick.",
        "Placer les nems sur une plaque à pâtisserie et les badigeonner d'un peu d'huile.",
        "Enfourner pendant 15 minutes ou jusqu'à ce qu'ils soient dorés et croustillants.",
        'Servir les nems chauds avec du riz et une sauce au choix.',
      ],
    },
    {
      id: 6,
      stars: 5,
      name: 'Rouleaux de Printemps Faits Maison',
      image: 'https://www.example.com/rouleaudeprintemps.jpg',
      author: 'Jane Doe',
      datePublished: '2023-01-30',
      description:
        'Des rouleaux de printemps croustillants et savoureux faits maison avec des ingrédients frais.',
      prepTime: 'PT45M',
      cookTime: 'PT10M',
      totalTime: 'PT55M',
      recipeYield: '12 rouleaux',
      recipeCategory: 'Entrée',
      recipeCuisine: 'Vietnamienne',
      nutrition: {
        calories: '100 calories par rouleau',
      },
      recipeIngredient: [
        '12 feuilles de galette de riz',
        '150g de vermicelles de riz',
        '12 feuilles de laitue',
        '12 tranches de saumon fumé',
        '12 tranches de concombre',
        '12 feuilles de coriandre',
        'Sauce hoisin pour servir',
      ],
      recipeInstructions: [
        "Faire tremper les vermicelles de riz dans de l'eau chaude pendant 15 minutes.",
        'Essorer les vermicelles et les couper en morceaux.',
        'Placer une feuille de galette de riz sur le plan de travail et y déposer une feuille de laitue, une tranche de saumon fumé, une tranche de concombre, des vermicelles et une feuille de coriandre.',
        "Rouler la feuille de galette de riz autour des ingrédients pour former un rouleau et le sceller avec un peu d'eau.",
        "Répéter l'opération avec les 11 autres feuilles de galette de riz.",
        'Servir les rouleaux avec de la sauce hoisin.',
      ],
    },
    {
      id: 7,
      stars: 5,
      name: 'Porc Croustillant à la Mijoteuse',
      image: 'https://www.example.com/porccroustillant.jpg',
      author: 'Jane Doe',
      datePublished: '2023-01-30',
      description:
        'Un porc juteux et croustillant à la mijoteuse avec des ingrédients simples et délicieux.',
      prepTime: 'PT15M',
      cookTime: 'PT6H',
      totalTime: 'PT6H15M',
      recipeYield: '6 portions',
      recipeCategory: 'Plat principal',
      recipeCuisine: 'Chinois',
      nutrition: {
        calories: '400 calories par portion',
      },
      recipeIngredient: [
        '1kg de poitrine de porc',
        '2 cuillères à soupe de miel',
        '2 cuillères à soupe de vinaigre de cidre de pomme',
        '1 cuillère à soupe de sauce soja',
        "2 gousses d'ail hachées",
        '1 cuillère à soupe de paprika',
        '1 cuillère à soupe de graines de sésame',
        '1 cuillère à soupe de sel',
        '1 cuillère à soupe de poivre noir',
      ],
      recipeInstructions: [
        "Mélanger le miel, le vinaigre de cidre de pomme, la sauce soja, l'ail haché, le paprika, les graines de sésame, le sel et le poivre noir dans un bol pour former la marinade.",
        'Placer la poitrine de porc dans un grand sac de congélation et ajouter la marinade.',
        'Fermer le sac et bien agiter pour que la marinade soit uniformément répartie sur le porc.',
        'Placer le sac dans le réfrigérateur et laisser mariner pendant au moins 4 heures, ou toute la nuit.',
        'Transférer le porc et la marinade dans une mijoteuse.',
        "Cuire le porc à feu bas pendant 6 heures, ou jusqu'à ce qu'il soit tendre et juteux.",
        'Servir le porc croustillant avec du riz ou des légumes verts.',
      ],
    },
    {
      id: 8,
      stars: 5,
      name: 'Bubble Tea Matcha',
      image: 'https://www.example.com/bubbleteamatcha.jpg',
      author: 'Jane Doe',
      datePublished: '2023-01-30',
      description: 'Un délicieux Bubble Tea Matcha parfumé et rafraîchissant.',
      prepTime: 'PT10M',
      cookTime: 'PT5M',
      totalTime: 'PT15M',
      recipeYield: '1 portion',
      recipeCategory: 'Dessert',
      recipeCuisine: 'Chinois',
      nutrition: {
        calories: '250 calories par portion',
      },
      recipeIngredient: [
        '200ml de lait entier',
        '2 cuillères à soupe de pâte de matcha',
        '2 cuillères à soupe de sucre',
        '1/2 sachet de gélatine',
        'Perles de tapioca',
        'Glace pilée',
      ],
      recipeInstructions: [
        'Mélanger le lait, la pâte de matcha et le sucre dans une casserole.',
        "Ajouter la gélatine et remuer jusqu'à ce qu'elle soit complètement dissoute.",
        "Chauffer la mixture à feu doux en remuant constamment jusqu'à ce qu'elle soit chaude.",
        'Verser la mixture dans un grand verre.',
        'Ajouter les perles de tapioca et la glace pilée.',
        'Remuer pour mélanger les ingrédients.',
        'Servir immédiatement et déguster.',
      ],
    },
    {
      id: 9,
      stars: 5,
      name: 'Che Riz Gluant au Lait de Coco',
      image: 'https://www.example.com/cherizgluantlaitdecoco.jpg',
      author: 'Jane Doe',
      datePublished: '2023-01-30',
      description:
        'Un dessert sucré et parfumé avec du riz gluant et du lait de coco.',
      prepTime: 'PT10M',
      cookTime: 'PT30M',
      totalTime: 'PT40M',
      recipeYield: '4 portions',
      recipeCategory: 'Dessert',
      recipeCuisine: 'Vietnamienne',
      nutrition: {
        calories: '250 calories par portion',
      },
      recipeIngredient: [
        '1 tasse de riz gluant',
        '1 tasse de sucre',
        '1 tasse de lait de coco',
        "1/2 tasse d'eau",
        '1 pincée de sel',
        'Des graines de sésame pour décorer',
      ],
      recipeInstructions: [
        "Rincer le riz gluant plusieurs fois à l'eau claire pour enlever le starch.",
        "Mettre le riz gluant dans une casserole avec l'eau.",
        "Couvrir et cuire à feu moyen-doux pendant environ 20 minutes, jusqu'à ce que l'eau soit complètement absorbée.",
        'Ajouter le sucre, le lait de coco et une pincée de sel dans la casserole.',
        "Remuer jusqu'à ce que le sucre soit dissous.",
        "Baisser le feu et cuire pendant environ 10 minutes, jusqu'à ce que la mixture soit épaisse et collante.",
        'Transférer la mixture de riz dans un bol et laisser refroidir.',
        'Saupoudrer de graines de sésame.',
        'Servir à température ambiante ou légèrement réfrigéré.',
      ],
    },
    {
      id: 10,
      stars: 5,
      name: 'Japchae',
      image: 'https://www.example.com/japchae.jpg',
      author: 'Jane Doe',
      datePublished: '2023-01-30',
      description:
        'Un plat coréen traditionnel avec des nouilles de pomme de terre et des légumes sautés.',
      prepTime: 'PT20M',
      cookTime: 'PT20M',
      totalTime: 'PT40M',
      recipeYield: '4 portions',
      recipeCategory: 'Dessert',
      recipeCuisine: 'Vietnamienne',
      nutrition: {
        calories: '250 calories par portion',
      },
      recipeIngredient: [
        '8 oz de nouilles de pomme de terre',
        '1 oignon, coupé en julienne',
        '2 carottes, coupées en julienne',
        '1/2 tasse de champignons shiitake, coupés en julienne',
        "2 gousses d'ail hachées",
        '1 tasse de bœuf haché cuit',
        '1 tasse de épinards hachés',
        '3 cuillères à soupe de sauce soja',
        '2 cuillères à soupe de sucre',
        "2 cuillères à soupe d'huile de sésame",
        '1 cuillère à soupe de graines de sésame grillées',
      ],
      recipeInstructions: [
        'Cuire les nouilles de pomme de terre selon les instructions du paquet.',
        "Rincer à l'eau froide et bien égoutter.",
        "Dans une poêle chaude, faire revenir l'oignon, les carottes, les champignons et l'ail dans l'huile de sésame pendant 5 minutes.",
        'Ajouter le bœuf haché et les épinards, et poursuivre la cuisson pendant 2 minutes.',
        'Ajouter la sauce soja, le sucre et les nouilles de pomme de terre aux légumes et au bœuf.',
        "Bien mélanger jusqu'à ce que tout soit bien enrobé.",
        'Transférer dans un plat de service et saupoudrer de graines de sésame grillées.',
        'Servir chaud.',
      ],
    },
  ];

  getRecipeById(recipeId: number): Recipe {
    const recipe = this.recipes.find((recipe) => recipe.id === recipeId);
    if (!recipe) {
      throw new Error('Oups, pas de recette!');
    } else {
      return recipe;
    }
  }
}
